version: '3.9'
services:
  aws-cli-container:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: aws-cli/Dockerfile
    container_name: awscli-container
    volumes:
      - .:/workdir
    env_file:
      - .env
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_DEFAULT_OUTPUT: json
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vue_app
    working_dir: /app
    volumes:
      - ./frontend/vite_fast:/app
    ports:
      - "15173:5173"
  db:
    build: 
      context: .
      dockerfile: postgres/Dockerfile
    ports:
      - 15433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGUSER=postgres
    volumes:
      - ./postgres/data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      retries: 5
    command: postgres -c log_statement=all
  # api:
  #   build:
  #     context: .
  #     dockerfile: api/django_api/Dockerfile
  #   container_name: api
  #   working_dir: /app
  #   tty: true
  #   # command: python manage.py runserver 0.0.0.0:8080
  #   ports:
  #     - "18080:8080"
  #   volumes:
  #     - ./api/django_api:/app
  #   depends_on:
  #     db:
  #       condition: service_healthy
  web:
    build: 
      context: .
      dockerfile: django-copilot/Dockerfile
    env_file:
      - .env
    ports:
      - "18000:8000"
    volumes:
      - ./django-copilot:/code
    depends_on:
      db:
        condition: service_healthy


